driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: chef/centos-6.5
  - name: chef/ubuntu-14.04

suites:
  - name: abiquo-collectd
    run_list:
      - recipe[abiquo-collectd]
    attributes:
      abiquo_collectd:
        endpoint: http://localhost
        app_key: app-key
        app_secret: app-secret
        access_token: access-token
        access_token_secret: access-token-secret
