driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: chef/centos-6.5
  - name: chef/ubuntu-14.04

suites:
  - name: collectd-abiquo
    run_list:
      - recipe[collectd-abiquo]
    attributes:
      collectd_abiquo:
        endpoint: http://localhost
        app_key: api-key
        app_secret: api-secret
        access_token: access-token
        access_token_secret: access-token-secret
